-- MySQL Script generated by MySQL Workbench
-- Fr 15 Mai 2020 10:47:23 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema SmallCL
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SmallCL
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SmallCL` DEFAULT CHARACTER SET utf8 ;
USE `SmallCL` ;

-- -----------------------------------------------------
-- Table `SmallCL`.`OType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SmallCL`.`OType` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `icon` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmallCL`.`CType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SmallCL`.`CType` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `icon` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmallCL`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SmallCL`.`User` (
  `UserName` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `VName` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `PWCN` TEXT(255) NOT NULL,
  `type` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`UserName`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmallCL`.`Object`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SmallCL`.`Object` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `ID_OType` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Object_OType_idx` (`ID_OType` ASC) VISIBLE,
  CONSTRAINT `fk_Object_OType`
    FOREIGN KEY (`ID_OType`)
    REFERENCES `SmallCL`.`OType` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmallCL`.`Template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SmallCL`.`Template` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Title` VARCHAR(45) NOT NULL,
  `CTitle` VARCHAR(45) NOT NULL,
  `CText` LONGTEXT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmallCL`.`SCLChange`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SmallCL`.`SCLChange` (
  `ID` BIGINT(255) NOT NULL AUTO_INCREMENT,
  `timestamp` DATETIME NOT NULL,
  `Title` VARCHAR(45) NOT NULL,
  `Text` LONGTEXT NOT NULL,
  `ID_User` VARCHAR(45) NOT NULL,
  `ID_CType` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Change_User1_idx` (`ID_User` ASC) VISIBLE,
  INDEX `fk_Change_CType1_idx` (`ID_CType` ASC) VISIBLE,
  CONSTRAINT `fk_Change_User1`
    FOREIGN KEY (`ID_User`)
    REFERENCES `SmallCL`.`User` (`UserName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Change_CType1`
    FOREIGN KEY (`ID_CType`)
    REFERENCES `SmallCL`.`CType` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmallCL`.`Change-Object`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SmallCL`.`Change-Object` (
  `Object_ID` INT NOT NULL,
  `SCLChange_ID` BIGINT(255) NOT NULL,
  INDEX `fk_Change-Object_Object1_idx` (`Object_ID` ASC) VISIBLE,
  INDEX `fk_Change-Object_SCLChange1_idx` (`SCLChange_ID` ASC) VISIBLE,
  PRIMARY KEY (`Object_ID`, `SCLChange_ID`),
  CONSTRAINT `fk_Change-Object_Object1`
    FOREIGN KEY (`Object_ID`)
    REFERENCES `SmallCL`.`Object` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Change-Object_SCLChange1`
    FOREIGN KEY (`SCLChange_ID`)
    REFERENCES `SmallCL`.`SCLChange` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SmallCL`.`token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SmallCL`.`token` (
  `session` VARCHAR(45) NOT NULL,
  `token` VARCHAR(45) NULL,
  `timestamp` DATETIME NULL,
  `User_UserName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`session`),
  INDEX `fk_token_User1_idx` (`User_UserName` ASC) VISIBLE,
  CONSTRAINT `fk_token_User1`
    FOREIGN KEY (`User_UserName`)
    REFERENCES `SmallCL`.`User` (`UserName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
